In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
df = pd.read_csv("Teen_Mental_Health_Dataset.csv")
df.head()

   age  gender  ...  addiction_level depression_label
0   14    male  ...                1                0
1   19  female  ...               10                0
2   17  female  ...                2                0
3   15    male  ...                9                0
4   15  female  ...                2                0

[5 rows x 13 columns]

In [12]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 16 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   age                          1200 non-null   int64
 1   gender                       1200 non-null   object
 2   daily_social_media_hours     1200 non-null   float64
 3   platform_usage               1200 non-null   object
 4   sleep_hours                  1200 non-null   float64
 5   screen_time_before_sleep     1200 non-null   float64
 6   academic_performance         1200 non-null   float64
 7   physical_activity            1200 non-null   float64
 8   social_interaction_level     1200 non-null   object
 9   stress_level                 1200 non-null   int64
 10  anxiety_level                1200 non-null   int64
 11  addiction_level              1200 non-null   int64
 12  depression_label             1200 non-null   int64
 13  gender_id                    1200 non-null   int64
 14  platform_id                  1200 non-null   int64
 15  social_interaction_level_id  1200 non-null   int64
dtypes: float64(5), int64(8), object(3)
memory usage: 150.1+ KB

In [8]:
label_encoder = LabelEncoder()
df['gender_id'] = label_encoder.fit_transform(df['gender'])
df["platform_id"] = label_encoder.fit_transform(df['platform_usage'])

In [11]:
#df["social_interaction_level"].unique()
social_interaction_level_dict = {"low":0, "medium":1, "high":2}
df["social_interaction_level_id"] = df["social_interaction_level"].map(social_interaction_level_dict)

In [13]:
df.drop(columns=["gender", "platform_usage", "social_interaction_level"], inplace=True)
df.head()

   age  daily_social_media_hours  ...  platform_id  social_interaction_level_id
0   14                       7.9  ...            1                            0
1   19                       1.9  ...            2                            2
2   17                       1.3  ...            1                            2
3   15                       7.4  ...            2                            1
4   15                       4.7  ...            0                            1

[5 rows x 13 columns]

In [14]:
df.columns

Index(['age', 'daily_social_media_hours', 'sleep_hours',
       'screen_time_before_sleep', 'academic_performance', 'physical_activity',
       'stress_level', 'anxiety_level', 'addiction_level', 'depression_label',
       'gender_id', 'platform_id', 'social_interaction_level_id'],
      dtype='object')

In [55]:
features = ['age', 'daily_social_media_hours', 'sleep_hours',
       'screen_time_before_sleep', 'academic_performance', 'physical_activity',
       'stress_level', 'anxiety_level', 'addiction_level', 'depression_label',
       'gender_id', 'platform_id']

target =  'social_interaction_level_id'

In [ ]:

from sklearn.linear_model import LogisticRegression


model = LogisticRegression()
model.fit(X_train_scaled, Y_train)  
Y_pred = model.predict(X_test_scaled)

In [46]:
X = df[features]
Y = df[target]

In [47]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

In [48]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [49]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=3, random_state=42)
model.fit(X_train_scaled, Y_train)  
Y_pred = model.predict(X_test_scaled)

In [50]:
from sklearn.metrics import classification_report, confusion_matrix,r2_score
print(classification_report(Y_test, Y_pred))

              precision    recall  f1-score   support

           0       0.37      0.54      0.44        85
           1       0.32      0.28      0.30        82
           2       0.33      0.21      0.25        73

    accuracy                           0.35       240
   macro avg       0.34      0.34      0.33       240
weighted avg       0.34      0.35      0.34       240

In [51]:
r2_score(Y_test, Y_pred)

-0.9250317662007623

In [52]:

from sklearn.linear_model import LogisticRegression


model = LogisticRegression()
model.fit(X_train_scaled, Y_train)  
Y_pred = model.predict(X_test_scaled)

In [53]:
r2_score(Y_test, Y_pred)
print(classification_report(Y_test, Y_pred))

              precision    recall  f1-score   support

           0       0.36      0.33      0.35        85
           1       0.38      0.51      0.44        82
           2       0.26      0.19      0.22        73

    accuracy                           0.35       240
   macro avg       0.34      0.34      0.34       240
weighted avg       0.34      0.35      0.34       240

In [54]:
from sklearn.svm import SVC
model = SVC(kernel='linear', random_state=42)
model.fit(X_train_scaled, Y_train)
Y_pred = model.predict(X_test_scaled)

In [42]:
print(classification_report(Y_test, Y_pred))

              precision    recall  f1-score   support

           0       0.35      0.49      0.41        85
           1       0.34      0.48      0.40        82
           2       0.25      0.01      0.03        73

    accuracy                           0.34       240
   macro avg       0.31      0.33      0.28       240
weighted avg       0.31      0.34      0.29       240